version: '3'
services:
  db:
    image: postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -q carrierwave,2 -q default
    volumes:
      - '.:/myapp'
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && tail -f /dev/null"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - "db:db"
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
volumes:
  redis:
